# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='metricsTable',
            fields=[
                ('hgnc', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('mean', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cov', models.DecimalField(decimal_places=5, max_digits=10)),
                ('mfc', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='gene_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinRefApp.metricsTable'),
        ),
    ]
