# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinRefApp', '0002_description_entrezid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='entrezid',
            field=models.TextField(),
        ),
    ]
