# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinRefApp', '0003_auto_20160501_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricstable',
            name='cov',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='metricstable',
            name='mean',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='metricstable',
            name='mfc',
            field=models.FloatField(),
        ),
    ]
